local path = minetest.get_modpath("bls_mobs")

dofile(path..'/mobs/black_widow.lua')
dofile(path..'/mobs/bloco.lua')
dofile(path..'/mobs/daddy_long_legs.lua')
dofile(path..'/mobs/echidna.lua')
dofile(path..'/mobs/giant_sandworm.lua')
dofile(path..'/mobs/icelamander.lua')
dofile(path..'/mobs/icesnake.lua')
dofile(path..'/mobs/lava_titan.lua')
dofile(path..'/mobs/manticore.lua')
dofile(path..'/mobs/moonheron.lua')
dofile(path..'/mobs/night_master.lua')
dofile(path..'/mobs/phoenix.lua')
dofile(path..'/mobs/sand_bloco.lua')
dofile(path..'/mobs/sandworm.lua')
dofile(path..'/mobs/scrausics.lua')
dofile(path..'/mobs/signosigno.lua')
dofile(path..'/mobs/snow_biter.lua')
dofile(path..'/mobs/stone_eater.lua')
dofile(path..'/mobs/uloboros.lua')
